# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-25 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import phonenumber_field.modelfields
import text_office.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, help_text='Sender number or name', max_length=32, null=True, verbose_name='Sender')),
                ('recipient', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Phone Number To')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'sent'), (1, 'failed'), (2, 'dispatched'), (3, 'queued')], db_index=True, null=True, verbose_name='Status')),
                ('priority', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'low'), (1, 'medium'), (2, 'high'), (3, 'now')], null=True, verbose_name='Priority')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('scheduled_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='The scheduled sending time')),
                ('context', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Context')),
                ('backend_alias', models.CharField(blank=True, default='', max_length=64, verbose_name='Backend alias')),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMS',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g: 'welcome_email'", max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description of this template.', verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, validators=[text_office.validators.validate_template_syntax], verbose_name='Content')),
                ('language', models.CharField(blank=True, default='', help_text='Render template in alternative language', max_length=12, verbose_name='Language')),
                ('default_template', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translated_templates', to='text_office.SMSTemplate', verbose_name='Default template')),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
            },
        ),
        migrations.AddField(
            model_name='sms',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='text_office.SMSTemplate', verbose_name='Message template'),
        ),
        migrations.AlterUniqueTogether(
            name='smstemplate',
            unique_together=set([('name', 'language', 'default_template')]),
        ),
    ]
